[application]
name = "odyssey_desktop"
asset_dir = "assets"

[bundle]
identifier = "com.odysseyarm.odyssey"
publisher = "OdysseyArm"

[web.resource]
style = ["/assets/tailwind.css"]

[web.resource.dev]
